ALTER TABLE "Answer" ADD COLUMN IF NOT EXISTS "filePublicId"     TEXT;
ALTER TABLE "Answer" ADD COLUMN IF NOT EXISTS "fileOriginalName" TEXT;
ALTER TABLE "Answer" ADD COLUMN IF NOT EXISTS "fileMimeType"     TEXT;
ALTER TABLE "Answer" ADD COLUMN IF NOT EXISTS "fileSizeBytes"    INTEGER;
